/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Atelier HR Design System - Material You
        "surface-tint": "#565e74",
        "outline-variant": "#b3b1b4",
        "secondary-container": "#e2e2e9",
        "primary-fixed-dim": "#ccd4ee",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed-variant": "#5b5672",
        "on-primary-container": "#4a5167",
        "surface-container-low": "#f6f3f4",
        "on-error": "#fff7f6",
        "inverse-on-surface": "#9e9c9d",
        "on-background": "#323235",
        "surface-dim": "#dbd9dd",
        "surface-bright": "#fcf8f9",
        "tertiary-container": "#e3dbfd",
        "surface-container-lowest": "#ffffff",
        "surface": "#fcf8f9",
        "surface-variant": "#e4e2e5",
        "surface-container": "#f0edef",
        "surface-container-high": "#eae7ea",
        "error-dim": "#4e0309",
        "inverse-primary": "#dae2fd",
        "tertiary": "#605c78",
        "on-primary": "#f7f7ff",
        "error": "#9f403d",
        "on-tertiary": "#fcf7ff",
        "secondary": "#5e5f65",
        "on-primary-fixed-variant": "#535b71",
        "on-tertiary-container": "#514d68",
        "primary-container": "#dae2fd",
        "on-primary-fixed": "#373f54",
        "secondary-fixed-dim": "#d4d4db",
        "primary-dim": "#4a5268",
        "secondary-fixed": "#e2e2e9",
        "on-tertiary-fixed": "#3e3a54",
        "tertiary-fixed": "#e3dbfd",
        "primary": "#565e74",
        "on-surface-variant": "#5f5f61",
        "on-error-container": "#752121",
        "on-secondary-fixed-variant": "#5a5b61",
        "inverse-surface": "#0e0e0f",
        "surface-container-highest": "#e4e2e5",
        "error-container": "#fe8983",
        "secondary-dim": "#525359",
        "on-surface": "#323235",
        "on-secondary-fixed": "#3e3f45",
        "tertiary-dim": "#54506b",
        "background": "#fcf8f9",
        "outline": "#7b7a7d",
        "on-secondary": "#f9f8ff",
        "tertiary-fixed-dim": "#d4cdee",
        "on-secondary-container": "#505157",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
